cargo-features = ["edition2024"]

[package]
name = "launch_lock"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
solana-program = "2.2.1"

[lib]
name = "launch_lock"
crate-type = ["cdylib", "lib"]